spring:
  config:
    import:
      - classpath:/application-dev.yml

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      check-template-location: true