spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pcmoa?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  resources:
    static-locations: classpath:/static/, file:/path/to/external/resources/

# 디버그 환경 추가 | ChoiDevv
logging:
  level:
    org:
      springframework: debug